### ISSUE TITLE
Provide wheel distribution on PyPI

### ISSUE THREAD

**Issue by edmorley** [Pylons/webtest#142]
Please could you provide a wheel archive on PyPI alongside the standard package? http://pythonwheels.com/

Many thanks :-)

**Comment by gawel** [comment]
done

**Comment by edmorley** [comment]
Many thanks :-)

**Comment by tseaver** [comment]
@edmorley can you help figure out how Webtest should build wheels, given its conditional dependencies?  @gawel released the wheel, which immediately broke downstream tests.

While we're at it, I still don't understand the drive to release wheels for packages without C extensions:  the difference in installation time is effectively immeasurable (especially once the local wheel cache is populated).

**Comment by gawel** [comment]
For now I'm using zest.releaser https://zestreleaser.readthedocs.org/en/latest/uploading.html#uploading-wheels The option is in my ~/.pypirc

**Comment by mmerickel** [comment]
You may find https://github.com/pypa/pip/issues/3025 interesting with regards to how to fix your setup.py. It links to a long thread with mike bayer on mako discussing the required markers.

**Comment by gawel** [comment]
I guess the solution is here: http://wheel.readthedocs.org/en/latest/#defining-conditional-dependencies

**Comment by gawel** [comment]
Looks good to me:

```
% pip install webtest
Downloading/unpacking webtest
Creating supposed download cache at /home/gawel/.buildout/tox/_download
  Downloading WebTest-2.0.20-py2-none-any.whl
  Storing download in cache at /home/gawel/.buildout/tox/_download/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2FW%2FWebTest%2FWebTest-2.0.20-py2-none-any.whl
Downloading/unpacking ordereddict (from webtest)
  Downloading ordereddict-1.1.tar.gz
  Storing download in cache at /home/gawel/.buildout/tox/_download/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fo%2Fordereddict%2Fordereddict-1.1.tar.gz
  Running setup.py (path:/home/gawel/tmp/tt/build/ordereddict/setup.py) egg_info for package ordereddict
Downloading/unpacking waitress>=0.8.5 (from webtest)
  Downloading waitress-0.8.10-py2-none-any.whl (119kB): 119kB downloaded
  Storing download in cache at /home/gawel/.buildout/tox/_download/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fpy2%2Fw%2Fwaitress%2Fwaitress-0.8.10-py2-none-any.whl
Downloading/unpacking WebOb>=1.2 (from webtest)
  Downloading WebOb-1.5.1-py2.py3-none-any.whl (79kB): 79kB downloaded
  Storing download in cache at /home/gawel/.buildout/tox/_download/https%3A%2F%2Fpypi.python.org%2Fpackages%2F3.4%2FW%2FWebOb%2FWebOb-1.5.1-py2.py3-none-any.whl
Downloading/unpacking six (from webtest)
  Downloading six-1.10.0-py2.py3-none-any.whl
  Storing download in cache at /home/gawel/.buildout/tox/_download/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fpy2.py3%2Fs%2Fsix%2Fsix-1.10.0-py2.py3-none-any.whl
Downloading/unpacking beautifulsoup4 (from webtest)
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB): 81kB downloaded
  Storing download in cache at /home/gawel/.buildout/tox/_download/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2Fb%2Fbeautifulsoup4%2Fbeautifulsoup4-4.4.1-py2-none-any.whl
Installing collected packages: webtest, ordereddict, waitress, WebOb, six, beautifulsoup4
  Running setup.py install for ordereddict
Successfully installed webtest ordereddict waitress WebOb six beautifulsoup4
Cleaning up...

% python
Python 2.6.9 (unknown, Aug 24 2014, 09:10:14) 
[GCC 4.8.2] on linux3
Type "help", "copyright", "credits" or "license" for more information.
>>> import ordereddict
>>> 

```

**Comment by dstufft** [comment]
> While we're at it, I still don't understand the drive to release wheels for packages without C extensions: the difference in installation time is effectively immeasurable (especially once the local wheel cache is populated).

It's nice not to need to populate the local cache at all. The metadata is also static so that makes it easier for other projects to inspect the artifact (particularly projects that interact with untrusted packages, since sdists require executing untrusted Python code in that case).

**Comment by edmorley** [comment]
Many thanks :-)
